### ISSUE TITLE
404 not found!

### ISSUE THREAD

**Issue by sunjieemm** [yangli-hub/CMMT-Code#1]
https://github.com/yangli-hub/CMMT-Code/blob/db2f036c1f0ad5ecf2ab56bc37db5b4ebd5ccea1/ANP_data/image%20label_folder#L1
Is this link correct, otherwise how can I get 404?

**Comment by yangli-hub** [comment]
The link has been updated in readme. (https://drive.google.com/file/d/17v9shne9W1j0wwgDsCCTJ4zUsKFSUxEw/view?usp=sharing).
You can try to copy the link into browser instead of directly clicking it via readme page.

**Comment by yangli-hub** [comment]
You can try to copy the link into browser instead of directly click it via readme page.
